export const COLOR_TOKENS = [
	"--color-canvas",
	"--color-surface",
	"--color-surface-2",
	"--color-surface-alt",
	"--color-sidebar",
	"--color-row-hover",
	"--color-border-subtle",
	"--color-border",
	"--color-border-2",
	"--color-border-strong",
	"--color-border-strong-2",
	"--color-text",
	"--color-text-bright",
	"--color-text-secondary",
	"--color-text-muted",
	"--color-text-dim",
	"--color-text-faint",
	"--color-text-faint-2",
	"--color-accent",
	"--color-accent-light",
	"--color-accent-pale",
	"--color-accent-deep",
	"--color-accent-deep-2",
	"--color-accent-tint-16",
	"--color-accent-tint-14",
	"--color-accent-tint-10",
	"--color-accent-tint-08",
	"--color-danger",
	"--color-danger-foreground",
	"--color-diff-add",
	"--color-diff-remove",
	"--color-accent-border",
] as const;

export const RADIUS_TOKENS = [
	"--radius-focus",
	"--radius-chip",
	"--radius-button",
	"--radius-section",
	"--radius-dialog",
] as const;
